//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Web.UserTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserTypeService.IUserTypeService")]
    public interface IUserTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserTypeService/GetAll", ReplyAction="http://tempuri.org/IUserTypeService/GetAllResponse")]
        HotelManagement.DTO.UserTypeDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserTypeService/GetUserType", ReplyAction="http://tempuri.org/IUserTypeService/GetUserTypeResponse")]
        HotelManagement.DTO.UserTypeDTO GetUserType(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserTypeService/Save", ReplyAction="http://tempuri.org/IUserTypeService/SaveResponse")]
        void Save(HotelManagement.DTO.UserTypeDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserTypeService/Delete", ReplyAction="http://tempuri.org/IUserTypeService/DeleteResponse")]
        void Delete(HotelManagement.DTO.UserTypeDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserTypeService/UserType", ReplyAction="http://tempuri.org/IUserTypeService/UserTypeResponse")]
        HotelManagement.DTO.UserTypeEnum UserType(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserTypeServiceChannel : HotelManagement.Web.UserTypeService.IUserTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserTypeServiceClient : System.ServiceModel.ClientBase<HotelManagement.Web.UserTypeService.IUserTypeService>, HotelManagement.Web.UserTypeService.IUserTypeService {
        
        public UserTypeServiceClient() {
        }
        
        public UserTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelManagement.DTO.UserTypeDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HotelManagement.DTO.UserTypeDTO GetUserType(int id) {
            return base.Channel.GetUserType(id);
        }
        
        public void Save(HotelManagement.DTO.UserTypeDTO obj) {
            base.Channel.Save(obj);
        }
        
        public void Delete(HotelManagement.DTO.UserTypeDTO obj) {
            base.Channel.Delete(obj);
        }
        
        public HotelManagement.DTO.UserTypeEnum UserType(int id) {
            return base.Channel.UserType(id);
        }
    }
}
