//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Web.UserMenuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserMenuService.IUserMenuService")]
    public interface IUserMenuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMenuService/GetAll", ReplyAction="http://tempuri.org/IUserMenuService/GetAllResponse")]
        HotelManagement.DTO.UserMenuDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMenuService/GetUserMenu", ReplyAction="http://tempuri.org/IUserMenuService/GetUserMenuResponse")]
        HotelManagement.DTO.UserMenuDTO GetUserMenu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMenuService/Save", ReplyAction="http://tempuri.org/IUserMenuService/SaveResponse")]
        void Save(HotelManagement.DTO.UserMenuDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMenuService/Delete", ReplyAction="http://tempuri.org/IUserMenuService/DeleteResponse")]
        void Delete(HotelManagement.DTO.UserMenuDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMenuService/GetByUser", ReplyAction="http://tempuri.org/IUserMenuService/GetByUserResponse")]
        HotelManagement.DTO.UserMenuDTO[] GetByUser(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserMenuServiceChannel : HotelManagement.Web.UserMenuService.IUserMenuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserMenuServiceClient : System.ServiceModel.ClientBase<HotelManagement.Web.UserMenuService.IUserMenuService>, HotelManagement.Web.UserMenuService.IUserMenuService {
        
        public UserMenuServiceClient() {
        }
        
        public UserMenuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserMenuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserMenuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserMenuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelManagement.DTO.UserMenuDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HotelManagement.DTO.UserMenuDTO GetUserMenu(int id) {
            return base.Channel.GetUserMenu(id);
        }
        
        public void Save(HotelManagement.DTO.UserMenuDTO obj) {
            base.Channel.Save(obj);
        }
        
        public void Delete(HotelManagement.DTO.UserMenuDTO obj) {
            base.Channel.Delete(obj);
        }
        
        public HotelManagement.DTO.UserMenuDTO[] GetByUser(int userId) {
            return base.Channel.GetByUser(userId);
        }
    }
}
