//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Web.HotelChainService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelChainService.IHotelChainService")]
    public interface IHotelChainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelChainService/GetAll", ReplyAction="http://tempuri.org/IHotelChainService/GetAllResponse")]
        HotelManagement.DTO.HotelChainDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelChainService/GetHotelChain", ReplyAction="http://tempuri.org/IHotelChainService/GetHotelChainResponse")]
        HotelManagement.DTO.HotelChainDTO GetHotelChain(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelChainService/Save", ReplyAction="http://tempuri.org/IHotelChainService/SaveResponse")]
        void Save(HotelManagement.DTO.HotelChainDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelChainService/Delete", ReplyAction="http://tempuri.org/IHotelChainService/DeleteResponse")]
        void Delete(HotelManagement.DTO.HotelChainDTO obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelChainServiceChannel : HotelManagement.Web.HotelChainService.IHotelChainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelChainServiceClient : System.ServiceModel.ClientBase<HotelManagement.Web.HotelChainService.IHotelChainService>, HotelManagement.Web.HotelChainService.IHotelChainService {
        
        public HotelChainServiceClient() {
        }
        
        public HotelChainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelChainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelChainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelChainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelManagement.DTO.HotelChainDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HotelManagement.DTO.HotelChainDTO GetHotelChain(int id) {
            return base.Channel.GetHotelChain(id);
        }
        
        public void Save(HotelManagement.DTO.HotelChainDTO obj) {
            base.Channel.Save(obj);
        }
        
        public void Delete(HotelManagement.DTO.HotelChainDTO obj) {
            base.Channel.Delete(obj);
        }
    }
}
