//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Web.HotelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelService.IHotelService")]
    public interface IHotelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetAll", ReplyAction="http://tempuri.org/IHotelService/GetAllResponse")]
        HotelManagement.DTO.HotelDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetHotel", ReplyAction="http://tempuri.org/IHotelService/GetHotelResponse")]
        HotelManagement.DTO.HotelDTO GetHotel(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Save", ReplyAction="http://tempuri.org/IHotelService/SaveResponse")]
        void Save(HotelManagement.DTO.HotelDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Delete", ReplyAction="http://tempuri.org/IHotelService/DeleteResponse")]
        void Delete(HotelManagement.DTO.HotelDTO obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelServiceChannel : HotelManagement.Web.HotelService.IHotelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServiceClient : System.ServiceModel.ClientBase<HotelManagement.Web.HotelService.IHotelService>, HotelManagement.Web.HotelService.IHotelService {
        
        public HotelServiceClient() {
        }
        
        public HotelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelManagement.DTO.HotelDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HotelManagement.DTO.HotelDTO GetHotel(int id) {
            return base.Channel.GetHotel(id);
        }
        
        public void Save(HotelManagement.DTO.HotelDTO obj) {
            base.Channel.Save(obj);
        }
        
        public void Delete(HotelManagement.DTO.HotelDTO obj) {
            base.Channel.Delete(obj);
        }
    }
}
