//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Web.BookingDetailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookingDetailService.IBookingDetailService")]
    public interface IBookingDetailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingDetailService/GetAll", ReplyAction="http://tempuri.org/IBookingDetailService/GetAllResponse")]
        HotelManagement.DTO.BookingDetailDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingDetailService/GetBookingDetail", ReplyAction="http://tempuri.org/IBookingDetailService/GetBookingDetailResponse")]
        HotelManagement.DTO.BookingDetailDTO GetBookingDetail(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingDetailService/Save", ReplyAction="http://tempuri.org/IBookingDetailService/SaveResponse")]
        void Save(HotelManagement.DTO.BookingDetailDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingDetailService/Delete", ReplyAction="http://tempuri.org/IBookingDetailService/DeleteResponse")]
        void Delete(HotelManagement.DTO.BookingDetailDTO obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingDetailServiceChannel : HotelManagement.Web.BookingDetailService.IBookingDetailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingDetailServiceClient : System.ServiceModel.ClientBase<HotelManagement.Web.BookingDetailService.IBookingDetailService>, HotelManagement.Web.BookingDetailService.IBookingDetailService {
        
        public BookingDetailServiceClient() {
        }
        
        public BookingDetailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingDetailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingDetailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingDetailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelManagement.DTO.BookingDetailDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HotelManagement.DTO.BookingDetailDTO GetBookingDetail(int id) {
            return base.Channel.GetBookingDetail(id);
        }
        
        public void Save(HotelManagement.DTO.BookingDetailDTO obj) {
            base.Channel.Save(obj);
        }
        
        public void Delete(HotelManagement.DTO.BookingDetailDTO obj) {
            base.Channel.Delete(obj);
        }
    }
}
