//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Web.RoomTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomTypeService.IRoomTypeService")]
    public interface IRoomTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTypeService/GetAll", ReplyAction="http://tempuri.org/IRoomTypeService/GetAllResponse")]
        HotelManagement.DTO.RoomTypeDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTypeService/GetRoom", ReplyAction="http://tempuri.org/IRoomTypeService/GetRoomResponse")]
        HotelManagement.DTO.RoomTypeDTO GetRoom(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTypeService/Save", ReplyAction="http://tempuri.org/IRoomTypeService/SaveResponse")]
        void Save(HotelManagement.DTO.RoomTypeDTO obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomTypeService/Delete", ReplyAction="http://tempuri.org/IRoomTypeService/DeleteResponse")]
        void Delete(HotelManagement.DTO.RoomTypeDTO obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomTypeServiceChannel : HotelManagement.Web.RoomTypeService.IRoomTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomTypeServiceClient : System.ServiceModel.ClientBase<HotelManagement.Web.RoomTypeService.IRoomTypeService>, HotelManagement.Web.RoomTypeService.IRoomTypeService {
        
        public RoomTypeServiceClient() {
        }
        
        public RoomTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelManagement.DTO.RoomTypeDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HotelManagement.DTO.RoomTypeDTO GetRoom(int id) {
            return base.Channel.GetRoom(id);
        }
        
        public void Save(HotelManagement.DTO.RoomTypeDTO obj) {
            base.Channel.Save(obj);
        }
        
        public void Delete(HotelManagement.DTO.RoomTypeDTO obj) {
            base.Channel.Delete(obj);
        }
    }
}
